### ISSUE TITLE
Product Metafields?

### ISSUE THREAD

**Issue by iamducke** [angeloashmore/gatsby-source-shopify#12]
can metafields be pulled in with a product?

**Comment by gil--** [comment]
`
{ products(first:10, query: "sku:123") {
  edges {
    node {
      metafields(first: 10) {
      	edges {
      		node {
      			key
      			value
                        namespace
      		}
      	}
      }
    }
  }
}
 }
`

that's the normal way. looks like metafields is simply missing from PRODUCTS_QUERY, PRODUCTS_QUERY

I'll look into making a PR to add support. I wonder if this is a new development as I feel like products did not support metafields via storefront api earlier this summer. 🤔

**Comment by iamducke** [comment]
thanks for investigating that, it's a shame shopify hasn't made that part of the storefront api, that's the most common way to get around their 100-variant limitation.. :frowning_face:

**Comment by angeloashmore** [comment]
I think eventually it’ll be worthwhile to integrate the admin API with the source plugin. Then we could get this kind of data.

**Comment by iamducke** [comment]
yeah, it's a necessity for me so I'm going to branch this repo and see if I can get it working on my own

**Comment by gil--** [comment]
@iamducke 

I don't know how much the new admin api differs from storefront but you can try changing https://github.com/angeloashmore/gatsby-source-shopify/blob/master/src/lib.js#L9 and seeing what happens.

Also if you're using Gatsby v2, you can checkout the graphql source plugin and directly use the admin plugin for metafield: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql

Additionally, I just released a Shopify plugin to work with Apollo to give live shop data and hydrate the client - https://github.com/gil--/gatsby-plugin-apollo-client

**Comment by iamducke** [comment]
I'll check these out, thank you so much!!

**Comment by iamducke** [comment]
@gil-- not sure if i should make an issue for this, i might just be being obtuse. I'm trying to upgrade to Gatsby v2 and this source is failing with a vague error message "an error occured while sourcing data". I followed all the migration steps and everything _seems_ right

When I revert back to v1 it's fine

**Comment by iamducke** [comment]
okaydoke, I can make that switch. Thanks for the quick feedback! You're both so fast!

**Comment by gil--** [comment]
Hmm, I'm actually using this with gatsby v2 `"gatsby": "next",` and the only issue I'm aware of is a deprecation notice due to the use of touchnode see #14. Maybe try moving *node_modules* to *node_modules_v1* and npm install the v2 plugins/dependencies?

**Comment by heart-of-code** [comment]
Hey! So, gatsby-source-graphql didn't work out because I didn't have fine enough control over how the queries were made and Shopify imposes very tight call limits on their Graphql Admin API. I ended up writing my own plugin, referencing this repo to help me learn how to build one. Is there some way to properly attribute you @angeloashmore ?
