### ISSUE TITLE
Querying product images

### ISSUE THREAD

**Issue by gilesbutler** [angeloashmore/gatsby-source-shopify#3]
Hey @angeloashmore 

Thanks for the awesome plugin!!

Very new to GraphQl so please excuse my ignorance if this is basic. I searched everywhere but I can't figure out how to get product images and variants to load.

Looking at the Shopify API docs and examples I would have thought it would be something like this...
```
{
  allShopifyProduct {
    edges {
      node {
        id
        title
        description
        descriptionHtml
        images(first: 250) {
          edges {
            node {
              src
            }
          }
        }
      }
    }
  }
}
```
And something similar for variants but they don't work. Am I missing something obvious or does the plugin maybe not support product image and varaiants yet?

Thanks

**Comment by gilesbutler** [comment]
Hey @angeloashmore, thanks for getting back to me.

No problem, I wouldn't be surprised if they'd updated the API. A lot of their own JS examples are out of date too.

In the end I went with an alternative gatsby plugin - [https://www.npmjs.com/package/gatsby-source-shopify-storefront](https://www.npmjs.com/package/gatsby-source-shopify-storefront)

It pulls in the images and variants like I mentioned using the following query. I presume your update will do something similar?

```
allShopifyProducts {
    edges {
      node {
        id
        title
        description
        descriptionHtml
        variants {
          edges {
            node {
              id
              title
              price
              selectedOptions {
                name
                value
              }
            }
          }
        }
        images {
          edges {
            node {
              id
              src
            }
          }
        }
      }
    }
  }
```

**Comment by angeloashmore** [comment]
This is completed in the `develop` branch. Will publish soon. Sorry for the unnecessary delay.
